### ISSUE TITLE
Request for Enhancement: Reset upstream keys for each scene

### ISSUE THREAD

**Issue by BCCUse** [meanstream-io/meanstream#12]
For each scene the system first starts by turning off any downstream keys.  It then properly either leaves the key off or turns it on depending on the scene.  

There's no such action for upstream keys.  Could you add something to the code that turns off each of the upstream keys for each scene/transition and then turns they back on if setup in the scene?

Thanks! Love the software!

**Comment by mathias-ewald** [comment]
Hi! Thanks (again) for reporting this :) I set up a quick example, so we can pin down the behavior that is wrong. I created a Scene "NOUSK1" that just shows "Camera1". The "WITHUSK" scene does the same but adds an USK on top. I added some comments for better understanding and reduced that to what we want to see:

```xml
    <Macro index="99" name="NOUSK1_2_WITHUSK" description="Cut Transition from NoUSK1 to WithUSK">

      <!-- Establish the NOUSK1 scene, to have a known state -->
      <Op id="PreviewInput" mixEffectBlockIndex="0" input="Camera1"/>

      <!-- Load the WITHUSK scene into preview -->
      <Op id="KeyType" mixEffectBlockIndex="0" keyIndex="0" type="Luma"/>
      <Op id="KeyFillInput" mixEffectBlockIndex="0" keyIndex="0" input="Camera1"/>
      <Op id="KeyCutInput" mixEffectBlockIndex="0" keyIndex="0" input="Camera1"/>
      <Op id="KeyMaskEnable" mixEffectBlockIndex="0" keyIndex="0" enable="False"/>
      <Op id="KeyFlyEnable" mixEffectBlockIndex="0" keyIndex="0" enable="True"/>
      <Op id="DVEAndFlyKeyXPosition" mixEffectBlockIndex="0" keyIndex="0" xPosition="0.0"/>
      <Op id="DVEAndFlyKeyYPosition" mixEffectBlockIndex="0" keyIndex="0" yPosition="0.0"/>
      <Op id="DVEAndFlyKeyXSize" mixEffectBlockIndex="0" keyIndex="0" xSize="0.5"/>
      <Op id="DVEAndFlyKeyYSize" mixEffectBlockIndex="0" keyIndex="0" ySize="0.5"/>
      <Op id="LumaKeyPreMultiply" mixEffectBlockIndex="0" keyIndex="0" preMultiply="True"/>

      <!-- Make sure the the USK is toggled (turned on in this case) -->
      <Op id="TransitionSource" mixEffectBlockIndex="0" source="Background, Key1"/>

      <!-- Run the transition -->
      <Op id="CutTransition" mixEffectBlockIndex="0"/>
    </Macro>
```

I think, you are suggesting to add

```
<Op id="KeyOnAir" mixEffectBlockIndex="0" keyIndex="0" onAir="False" />
```

to the the macro at some point before the "CutTransition" operation, correct? The problem I see that that is that `KeyOnAir` manipulates the program output. If you had a source scene that shows USK 1 and a target scene that shows it too, you would 

1) Disable the USK in the program output
2) Enable it in the preview output
3) Run the transition

In case of a Cut transition, it would probably be just a quick flicker (which is bad enough) but in the case of any other transition that takes a while to complete, it would be strange to see the USK disappear just like that in step 1.

If I am misunderstanding you or something is factually wrong, please correct me :)

**Comment by BCCUse** [comment]
I see what you mean with the use case of one scene to another that both
have an upstream key.  In that case, I suppose that you wouldn't have to
worry about disabling the upstream key before the transition.  You only
have to make sure that the upstream key in the preview is correct.
However, what happens when you transition to a scene without an upstream
key. It appears to me that the key would be left enabled in the program
output.

My first bug report shows that upstream keys don't get enabled in the
program output when they're only setup in the preview.  I'm still learning
the system.  You're obviously much more skilled than I am.  I'm going to
setup the same scene and check carefully what's happening in both preview
and program so that I can better follow the code.  I'll get right back to
you.

Thanks again.

Joe

**Comment by mathias-ewald** [comment]
Just for explanation: The TransitionSource operation tells the ATEM whether to toggle the state of the USK on the next transition. That means, when the USK 1 is OFF and will be ON, "Key1" will be in the list of the TransitionSource operation. If USK 1 is ON and will be OFF, it is listed an the TransitionSource operation, too! Only if it is OFF and should remain OFF, or ON and should remain ON, then TransitionSource will not have it in the list.

There is no case, that uses preview/program transitioning, that explicitly uses the KeyOnAir operation. This is the case for the transition types cut, dip, mix, wipe and dve.
