### ISSUE TITLE
DVE Box not showing up in Preview using Windows Edge browser (Win 11)

### ISSUE THREAD

**Issue by walkman04** [meanstream-io/meanstream#47]
If a user wants to create a DVE scene, the DVE box will not show up in Preview when using MS Edge browser, hence a given user cannot define the box. 

<img width="995" alt="Edge Bug" src="https://user-images.githubusercontent.com/117432629/207251100-621ce784-4070-4817-ac12-0837d21eb664.png">

**Comment by mathias-ewald** [comment]
The problem seems to be with the CSS `clip-path` property. 

When the CSS property is set to 
 
```
clip-path: inset(calc(0%) calc(100%));
```

the element is rendered at will size in FF and Chrome but completly clipped off in Edge.
